spring.application.name=auth-server
server.port=9000
# DataSource
spring.datasource.url=jdbc:sqlserver://ec2-XX-XXX-XXXX-XX.compute-1.amazonaws.com:1433;databaseName=XXXX_XXXX_XXXX;encrypt=false;trustServerCertificate=false
spring.datasource.username=XXXX
spring.datasource.password=XXXXX
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.properties.hibernate.format_sql=true

#dev options
server.servlet.session.cookie.name=APP_SESSION
logging.level.org.springframework.security=DEBUG
